### ISSUE TITLE
Add support for mender-partuuid

### ISSUE THREAD

**Issue by crballentine-ess** [coreycothrum/meta-mender-kernel#8]
I've been trying to get Secure Boot implemented on a system that uses Mender for updates over USB. Following the very thorough examples I was able to add meta-mender-kernel and the required layers and configuration changes.

Unfortunately, we use mender-partuuid and we receive the following error:
ERROR: mender-kernel does not currently support mender-partuuid

Is mender-partuuid support in a planned release?

**Comment by coreycothrum** [comment]
This is a restriction from [`meta-mender-core`](https://github.com/mendersoftware/meta-mender/tree/master/meta-mender-core)

```
        if [ ${partuuid} = "true" ]; then
            bbfatal "MENDER_EXTRA_PARTS and DISTRO_FEATURE 'mender-partuuid' are both defined and incompatible"
        fi
```
https://github.com/mendersoftware/meta-mender/blob/e0b2faf307a621cb1847c2991aa26016b3854f23/meta-mender-core/classes/mender-setup-image.inc#L64

----
I haven't put much thought into it, as this fit my use case OK. I'm not opposed to supporting it.... though it'd require PRs in `meta-mender`.

**Comment by Alvenix** [comment]
The restriction was removed with the addition of MENDER_EXTRA_PARTS_UUID variable. I have sent PRs to meta-mender-kernel and meta-mender-luks

**Comment by coreycothrum** [comment]
@Alvenix thanks for the PRs. First glance looks OK to me. I should have time this week to do a build and confirm.

**Comment by Alvenix** [comment]
> @Alvenix thanks for the PRs. First glance looks OK to me. I should have time this week to do a build and confirm.

Thanks! I would like to note that for me I had to do fresh builds to test correctly. (It seems to me, caching doesn't play nice with meta-bitbake-variable-substitution)
